### ISSUE TITLE
Soundness bug in while prover

### ISSUE THREAD

**Issue by ngorogiannis** [ngorogiannis/cyclist#3]
One example I'm working on for the extended while prover (with ordinal labels) is Floyd's cycle detection algorithm.

I thought I would run it through the while abducer to see what it came up with. Doing so has uncovered a bug.

The program (for simplicity, does not work on acyclic lists):

fields: next;
precondition: P(x);
t := x;
if x != nil then
  h := x.next;
  while h != t do
    t := t.next;
    h := h.next;
    h := h.next
  od
fi

The output of running while_abduce on it:

reubrowe$ ./while_abduce.native -P tests/whl_abd/floyd-cycle.wl -pd -p
0: P^1(x) |- t := x; ... (Assign) [1]
  1: x=t \* P^1(x) |- if x!=nil then ... fi (P L.Unf.) [2, 3]
    2: nil=t \* x=t \* I002^1(x) |- if x!=nil then ... fi (If(det)) [4]
      4: nil=t \* x=t \* I002^1(x) |-  (Empty)
    3: x=t \* nil!=x \* I001^1(x) |- if x!=nil then ... fi (If(det)) [5]
      5: x=t \* nil!=x \* I001^1(x) |- h := x.next; ... (I001 L.Unf.) [6]
        6: x=t \* nil!=x \* x->nil \* I003^1(x, nil) |- h := x.next; ... (Load) [7]
          7: nil=h \* x=t \* nil!=x \* x->nil \* I003^1(x, nil) |- while h!=t do ... od (While(det)) [8]
            8: nil=h \* x=t \* nil!=x \* x->nil \* I003^1(x, nil) |- t := t.next; ... (Load) [9]
              9: nil=h \* x=h \* t=h \* nil!=x \* x->nil \* I003^1(x, nil) |- h := h.next; ... (Ex Falso)

P {
nil=a => P(a) |
nil!=a \* I001^1(a) => P(a)
} ;

I001 {
nil!=a \* a->nil => I001(a)
}

The application of the Ex Falso axiom in node 9 is incorrect, but is allowed because of the equality x=h. I cannot figure out how this equality is generated, but it does not actually hold at that point in the program.

**Comment by ngorogiannis** [comment]
Hi Reuben,

I've been trying to debug the report you made.  I tried it running on the current master, and I don't see the same behaviour (proof, or incorrect subgoals generated by Load).  This of course does not mean there is no bug, but I can't trigger it on master any more.

I then realised I fixed some bugs in the existential variable handling back in Feb/March which I guess have not been merged in your branch.  This _could_ explain what you see on your branch.

I tried checking out ordinal-labels to see for myself.  However, I ran against a compilation bug (!).  

```
Error: This expression has type 'a list
       but an expression was expected of type
         Sl_form.t = Ord_constraints.t * Sl_heap.t list
Command exited with code 2.
```

I wonder if this is an OCaml version issue, as I recently updated to 4.02.

In the long term, it would be sensible to try and merge all commits from master that cause no issues/conflicts.  This will make it easier to merge the problematic bits later.

Nikos

**Comment by reubenrowe** [comment]
Hmm,

That's weird - I think I must have run the test on while_abduce in (some 
version of) the master branch, because I'm fairly sure the changes I've 
made are not compatible with the code for the while abducer.

I will check this when I get in to the office today.

On the ordinal_labels branch, only the extended_while_prove.native and 
sl_prove.native will compile.

So, yes, there will be more work involved in merging my changes with the 
master branch than may have been evident from what I have said previously!

**Comment by reubenrowe** [comment]
Hi Nikos,

So, I was running this in my working copy - i.e. with all my changes on 
ordinal_labels. However, I was running a version of while_abduce.native 
that was compiled in September - so before I split off the 
ordinal_labels branch.

Perhaps this suggests that the bug has been fixed by your changes 
earlier this year.

R

**Comment by ngorogiannis** [comment]
I'll close this, as it seems we can't reproduce this any more. Plus, there is already a regression test that I /believe/ would catch this.
